"""Agrega campo ubicacion a Producto

Revision ID: 8a7887dea207
Revises: aef92a05179e
Create Date: 2025-07-29 18:54:06.376896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7887dea207'
down_revision = 'aef92a05179e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('idx_categoria'))
        batch_op.drop_index(batch_op.f('idx_proveedor'))
        batch_op.drop_constraint(batch_op.f('componentes_ibfk_2'), type_='foreignkey')

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='COT-2024-001',
               existing_nullable=True)
        batch_op.alter_column('componentes',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='IDs, cantidades y precios',
               existing_nullable=False)
        batch_op.alter_column('servicios',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='IDs de servicios',
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='COP',
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('numero_factura',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False,
               comment=None,
               existing_comment='FAC-2024-001')
        batch_op.alter_column('iva',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Valor en COP',
               existing_nullable=False)
        batch_op.alter_column('fecha_emision',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.alter_column('referencia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Factura/Remisión',
               existing_nullable=True)
        batch_op.alter_column('fecha',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_index(batch_op.f('idx_tipo'))

    with op.batch_alter_table('ordenes_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('pendiente', 'en_proceso', 'completado', 'cancelado', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.drop_index(batch_op.f('codigo'))
        batch_op.drop_index(batch_op.f('idx_estado'))
        batch_op.drop_index(batch_op.f('idx_fecha'))
        batch_op.drop_constraint(batch_op.f('ordenes_servicio_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ordenes_servicio_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ordenes_servicio_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('cliente_id')
        batch_op.drop_column('diagnostico')
        batch_op.drop_column('tecnico_id')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('componentes_usados')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('codigo')
        batch_op.drop_column('costo_final')
        batch_op.drop_column('servicio_id')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='SV-ENS-001',
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('ensamblaje', 'soporte', 'mantenimiento', 'reparacion', 'diagnostico', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('precio_base',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               comment=None,
               existing_comment='COP')
        batch_op.alter_column('duracion_estimada',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Minutos',
               existing_nullable=True)
        batch_op.alter_column('requisitos',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('activo', 'inactivo', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'"))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               nullable=False,
               comment=None,
               existing_comment='DNI/NIT')
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               comment=None,
               existing_comment='Hash bcrypt',
               existing_nullable=False)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('admin', 'proveedor', 'tecnico', 'inventario', 'contabilidad', 'cliente', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('activo', 'inactivo', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'"))
        batch_op.alter_column('fecha_registro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_estado'))
        batch_op.drop_index(batch_op.f('idx_rol'))
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.create_index(batch_op.f('idx_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('idx_estado'), ['estado'], unique=False)
        batch_op.alter_column('fecha_registro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('estado',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('activo', 'inactivo', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'"))
        batch_op.alter_column('rol',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'proveedor', 'tecnico', 'inventario', 'contabilidad', 'cliente', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Hash bcrypt',
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('documento',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               comment='DNI/NIT')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('activo', 'inactivo', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'"))
        batch_op.alter_column('requisitos',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('duracion_estimada',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               comment='Minutos',
               existing_nullable=True)
        batch_op.alter_column('precio_base',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               nullable=False,
               comment='COP')
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('ensamblaje', 'soporte', 'mantenimiento', 'reparacion', 'diagnostico', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
        batch_op.alter_column('codigo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               comment='SV-ENS-001',
               existing_nullable=True)

    with op.batch_alter_table('ordenes_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('costo_final', mysql.INTEGER(), autoincrement=False, nullable=True, comment='COP incluyendo componentes'))
        batch_op.add_column(sa.Column('codigo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='OS-2024-001'))
        batch_op.add_column(sa.Column('fecha_fin', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('componentes_usados', mysql.JSON(), nullable=True, comment='IDs y cantidades'))
        batch_op.add_column(sa.Column('observaciones', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('tecnico_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diagnostico', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ordenes_servicio_ibfk_3'), 'usuarios', ['tecnico_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ordenes_servicio_ibfk_2'), 'servicios', ['servicio_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ordenes_servicio_ibfk_1'), 'usuarios', ['cliente_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_fecha'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('idx_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('codigo'), ['codigo'], unique=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('pendiente', 'en_proceso', 'completado', 'cancelado', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_fecha'), ['fecha'], unique=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('referencia',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Factura/Remisión',
               existing_nullable=True)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('fecha_emision',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('iva',
               existing_type=mysql.INTEGER(),
               comment='Valor en COP',
               existing_nullable=False)
        batch_op.alter_column('numero_factura',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               comment='FAC-2024-001')

    with op.batch_alter_table('detalle_factura', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('total',
               existing_type=mysql.INTEGER(),
               comment='COP',
               existing_nullable=False)
        batch_op.alter_column('servicios',
               existing_type=mysql.JSON(),
               comment='IDs de servicios',
               existing_nullable=True)
        batch_op.alter_column('componentes',
               existing_type=mysql.JSON(),
               comment='IDs, cantidades y precios',
               existing_nullable=False)
        batch_op.alter_column('codigo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='COT-2024-001',
               existing_nullable=True)

    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('componentes_ibfk_2'), 'usuarios', ['proveedor_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_proveedor'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_categoria'), ['categoria_id'], unique=False)
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###
